# Site settings
title: Munyao Festus Kaleli
email:
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: username
github_username: username
minimal_mistakes_skin: neon
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
# Removed pagination to disable post listing
# paginate: 5
# paginate_path: /page:num/
timezone:

include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author profile settings
author:
  name   : "Munyao Festus"
  avatar : "/assets/images/IMG_5350.jpg"
  bio    : "Believer & Citizen of God's kingdom, Cyber Security."
  links:
    - label: "Credly"
      icon: "fas fa-fw fa-link"
      url: "https://www.credly.com/badges/d111421c-e5b9-4474-8a8e-1e6046837d74/public_url"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/munyao-mwendwa-9871211a9"

# Footer links
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"

# Defaults
defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: splash
      author_profile: true

# Archives (optional, safe to keep)
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
